[package]
name = "vttf"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = "4.5.23"
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
