name: Rust

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Get release version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
    
    - name: Build
      run: cargo build --release
    
    - name: Package
      run: |
        mkdir -p vttf/DEBIAN
        mkdir -p vttf/usr/local/bin
        cp target/release/vttf vttf/usr/local/bin/
        echo "Package: vttf
        Version: ${{ env. VERSION }}
        Section: base
        Priority: optional
        Architecture: amd64
        Maintainer: Andrey Chushkin <andrey@chushkin.tech>
        Description: Tool to convert Vault secret data to Terraform environment variables." > vttf/DEBIAN/control
        dpkg-deb --build vttf
        mv vttf.deb vttf_${{ env.VERSION }}_amd64.deb
    
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: vttf_${{ env.VERSION }}_amd64.deb
        make_latest: true